version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 50051:50051
    networks:
      - movies
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies
      POSTGRES_DB: movies
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - movies
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
    networks:
      - movies
volumes:
  postgres_data:


networks:
  movies:
